name: publish-docker

on:
  release:
    types:
      - created

jobs:
  # Set release version
  version:
      name: Set release version
      runs-on: ubuntu-latest
      outputs:
        release-version: ${{ steps.release-version-step.outputs.RELEASE_VERSION }}
      steps:
        - id: release-version-step
          run: echo "::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}"
        
  # Build docker image and publish to registry:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: biensupernice/krane-ui
          tags: latest, ${{ env.RELEASE_VERSION }}
        env: 
            RELEASE_VERSION: ${{ needs.version.outputs.release-version }}
